services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"  
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/sistema_db
      - MONGODB_URL=mongodb://admin:admin123@mongo:27017/
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: unless-stopped

  sql-consumer:
    build:
      context: ./backend
    command: python consumers/sql_consumer.py
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/sistema_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    restart: unless-stopped
    deploy:
      replicas: 2 

  nosql-consumer:
    build:
      context: ./backend
    command: python consumers/nosql_consumer.py
    environment:
      - MONGODB_URL=mongodb://admin:admin123@mongo:27017/
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: unless-stopped
    deploy:
      replicas: 1

  postgres:
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sistema_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sistema_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data: